// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "http://localhost:5432";
const SUPABASE_ANON_KEY = "local_development_key";

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});



console.log("🔄 Loading supabase from: src/integrations/supabase/client.ts");




// This file is automatically generated. Do not edit it directly.
//import { createClient } from '@supabase/supabase-js';
//import type { Database } from './types';

//const SUPABASE_URL = "http://localhost:5432";
//const SUPABASE_PUBLISHABLE_KEY = "local_development_key";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

//export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);